services:
  api:
    image: ghcr.io/caiomaz/gorfe:latest
    ports:
      - "4000:4000"
    environment:
      - RUST_LOG=info
      - SENTRY_DSN=${SENTRY_DSN}
    networks:
      - gorfe-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL}
      - REPO_USER=${REPO_USER}
      - REPO_PASS=${REPO_PASS}
    networks:
      - gorfe-network

networks:
  gorfe-network:
    driver: bridge