services:
  api:
    image: ghcr.io/caiomaz/gorfe:latest
    ports:
      - "4000:4000"
    environment:
      - RUST_LOG=info
      - SENTRY_DSN=https://f10ec06978e996aea2a2542c5320f9da@o4508631411064832.ingest.us.sentry.io/4508632300847104
    networks:
      - gorfe-network
    
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - gorfe-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - gorfe-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    networks:
      - gorfe-network

    k6:
      image: loadimpact/k6
      volumes:
      - ./load_test.js:/load_test.js
      entrypoint: ["k6", "run", "/load_test.js"]
      networks:
      - gorfe-network
      command: ["sleep", "infinity"]

networks:
  gorfe-network:
    driver: bridge