# Configuração do Dependabot para atualizações automáticas de dependências em projetos Rust.
version: 2
updates:
  - package-ecosystem: "cargo" # Gerenciador de pacotes do Rust
    directory: "/" # Diretório onde o arquivo Cargo.toml está localizado
    schedule:
      interval: "weekly" # Verificar atualizações semanalmente
    commit-message:
      prefix: "deps" # Prefixo das mensagens de commit
    open-pull-requests-limit: 10 # Limite de PRs abertos simultaneamente
    rebase-strategy: "auto" # Fazer rebase automaticamente quando necessário
    labels:
      - "dependencies" # Adiciona uma label específica para PRs gerados pelo Dependabot
